name: deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. SSH 키 설정
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3. 서버 호스트 키 등록
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_PUBLIC_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # 4. SSH 접속 후 배포
      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=yes ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_PUBLIC_IP }} "
            cd express
            git pull || exit 1
            npm install || exit 1
            npm run build || exit 1
            sudo pkill node || true
            npm run start & npx wait-on http://localhost
            exit
          "

