name: deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. SSH 키 설정
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3. 서버 호스트 키 등록
      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_PUBLIC_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # 4. SSH 접속 후 배포
      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=yes ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_PUBLIC_IP }} "
            # nvm 환경 로드 (필요한 경우)
            export NVM_DIR=\"$HOME/.nvm\"
            [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\"
            nvm use 20 || true

            # PATH 추가 (Node.js 설치 위치 확인 후 필요 시 조정)
            export PATH=\$PATH:/usr/local/bin

            # 프로젝트 디렉토리 이동
            cd express

            # Git 서버 브랜치 동기화
            git fetch origin dev || exit 1
            git reset --hard origin/dev || exit 1

            # Node.js 패키지 설치 및 빌드
            npm install || exit 1
            npm run build || exit 1

            # 기존 Node 프로세스 종료
            sudo pkill node || true

            # 앱 백그라운드 실행
            npm run start &

            # 서버가 시작될 때까지 대기
            npx wait-on http://localhost

            exit
          "
