name: deploy

on:
    push:
        branches:
        - dev

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Set up SSH
              run: |
                mkdir -p ~/.ssh/
                echo "${{ secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                
            - name: Set up Known hosts
              run: | 
                ssh-keyscan -H ${{ secrets.SSH_PUBLIC_IP }} >> ~/.ssh/known_hosts
                chmod 644 ~/.ssh/known_hosts
            
            - name: SSH and deploy
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_PUBLIC_IP }} "
                  export NVM_DIR=\$HOME/.nvm
                  [ -s \"\$NVM_DIR/nvm.sh\" ] && \. \"\$NVM_DIR/nvm.sh\"
                  [ -s \"\$NVM_DIR/bash_completion\" ] && \. \"\$NVM_DIR/bash_completion\"
                  cd express
                  git pull || exit 1
                  npm install || exit 1
                  npm run build || exit 1
                  sudo pkill -f node || true
                  nohup npm start > app.log 2>&1 &
                  npx wait-on http://localhost:80
                  exit
                  "
