name: testAndDeploy

on:
  push:
    branches:
      - master

permissions:
  id-token: write # this is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository # 코드 불러오기
        uses: actions/checkout@v3

      - name: Set up Docker Compose # 깃허브 액션에서 도커 설치
        uses: docker/setup-buildx-action@v3

      - name: Build and test with Docker compose # 빌드와 테스트
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::044260498537:role/githubChoe-Jong-Geon_express_OIDC
          role-session-name: samepleSessionName
          aws-region: ${{env.AWS_REGION}}
          

       
  