name: testAndDeploy

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository # 코드 불러오기
        uses: actions/checkout@v3

      - name: Node.js setup       # Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install npm packages
        run: npm ci

      - name: Install and run redis-server
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          redis-server --daemonize yes --requirepass test_env --port 6380

      - name: Run test
        run: npm run test:ci

      - name: Test build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Set up Known hosts
        run: |
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_PUBLIC_IP }} "
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v20.19.4/bin
            cd express
            git pull || exit 1
            npm install || exit 1
            npm run build || exit 1
            sudo pkill node || exit 1
            nohup npm run start > app.log 2>&1 &
            exit
          "
